### PR TITLE
Search by tags in html report

### PR DESCRIPTION
**Pull request by ravxz**
Introduced search by tags in html report.
Use "tag:" prefix for search by tags (as commma-separated list). E.g. type in search field: "tag:tag1,tag2".
File suites.json is enhanced by "tags" field.

### CODE REVIEW

**Comment by ravxz** [comment]
Hi! Could you please consider this improvement to Allure HTML report search facilities?

**Comment by ravxz** [comment]
@baev, could you please consider this pull request and help with review checks?

**Comment by baev** [comment]
@ravxz thanks for the contribution! Could you please fix the build and sign the CLA

**Comment by baev** [comment]
> @baev, I fixed the build and signed the CLA.

you need to link your commits with your GH user

> Ravil Zakirov seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by ravxz** [comment]
@baev , my e-mail seems to be linked to my GH account according to the instruction. Could you please provide issue details?

**Comment by baev** [comment]
Screenshot 2022-04-26 at 18 36 00

make sure the following email is specified in your Github profile. If everything is done correctly you'll see your GH profile avatar near the commit messages:


Screenshot 2022-04-26 at 18 36 59

In case you willing to use the different email, you need to update your local git config and remake the commits (the easiest way is to rebase everything from master or sort reset and re-commit)

**Comment by ravxz** [comment]
@baev , thanks! Created another pull request.

**Pull request closed without merging**
