### PR TITLE
Use Jest as a frontend testing tool (closes #189)

### LINKED ISSUE #189: Replace Jasmine with Jest
Jest includes some nice defaults, that now we are configuring manually: https://github.com/allure-framework/allure2/blob/master/allure-web/test/bootstrap.js

Test codebase will not be changed, because Jest and Jasmine has the same API

### PR DESCRIPTION
**Pull request by just-boris**

### CODE REVIEW

**Comment by just-boris** [comment]
Finally, the coverage report works. Numbers are not good, though:

image

**Comment by just-boris** [comment]
FYI @cpojer, there is an example of Jest setup for Backbone+Handlebars stack.

**Comment by baev** [comment]
@just-boris thanks!

**Comment by cpojer** [comment]
@just-boris that's awesome. Can I encourage you to write a blog post about all of this? :)

**Comment by just-boris** [comment]
Maybe. Here I have implemented a Handlebars transformer. It can be extracted as a separate package and then presented via blog post.

**Pull request merged**
