### PR TITLE
Add data-tooltips to side navigation icons

### PR DESCRIPTION
**Pull request by leonsabr**
### Context
In collapsed state this tooltips really help for newbies. New rule: no data-tooltips in Expanded state.

tooltip

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] ~~Provide unit tests~~ this is just an icon's tooltip

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by baev** [comment]
@leonsabr could you please rebase and fix eslint issues:

```
/home/jenkins/workspace/allure2_PR-406-IVALK3T4KECVVADYDPI7Z7ECZ27P5BEPAU2C5RDQFQNKSV573WCA/allure-generator/src/main/javascript/components/side-nav/SideNavView.js
  2:24  error  'behavior' is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

```

**Comment by leonsabr** [comment]
I have squashed all commits.

**Comment by just-boris** [comment]
@baev it just makes me curious, why did you remove the tooltip here: https://github.com/allure-framework/allure2/commit/38836f7f138effd58ee9f8f61297b605d4e5861e

**Comment by leonsabr** [comment]
Second commit adds translations for `Expand` tooltip.

**Comment by baev** [comment]
@leonsabr thanks!

**Pull request merged**
