### PR TITLE
Get rid of flex boxes for charts, due to IE problems (fixes #228)

### LINKED ISSUE #228: Duration graph broken in IE11

### PR DESCRIPTION
**Pull request by just-boris**
My mad skills in action. Did not expect, that it would be still actual in 2k17

### CODE REVIEW

**Comment by baev** [comment]
@sseliverstov could you please check this out

**Comment by just-boris** [comment]
Build has been failed, my apologies.
Will fix it this evening.

**Comment by just-boris** [comment]
Fixed. Enjoy!

**Comment by baev** [comment]
@just-boris thanks!

**Pull request merged**
