### PR TITLE
Introduced search by tags in html report

### PR DESCRIPTION
**Pull request by ravxz**
Introduced search by tags in html report.
Use "tag:" prefix for search by tags (as commma-separated list). E.g. type in search field: "tag:tag1,tag2".
File suites.json is enhanced by "tags" field.

### CODE REVIEW

**Comment by ravxz** [comment]
@baev, could you please help with merging this pull request to the master?

**Comment by ravxz** [comment]
@baev , when this pull request is planned to merge into master? Which date is the next release coming?

**Comment by ravxz** [comment]
@baev, it this pull request going to be merged into master for next release?

**Comment by baev** [comment]
> it this pull request going to be merged into master for next release?

yes, it will. I'd expect 2.19 next week

**Comment by ravxz** [comment]
@baev, are they any news on release 2.19 with this fix?

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
@ravxz sorry for the delay

thanks for the contribution! 👍

**Comment by ravxz** [comment]
@baev, ok!

**Comment by olivia2046** [comment]
> Introduced search by tags in html report. Use "tag:" prefix for search by tags (as commma-separated list). E.g. type in search field: "tag:tag1,tag2". File suites.json is enhanced by "tags" field.

Hello @ravxz Ravil, not sure whether this is the right place to ask this question: I've updated allure-pytest, jenkins allure plugin/allure command line tool to latest version, but still get no result using tag: tag1, or tag1 in search box. 
Is this the correct place to do search?
image
image

Anything else I need to do to get this work for me? Thanks.

**Comment by olivia2046** [comment]
and i see tags node in suites.json
image

**Comment by baev** [comment]
@olivia2046, please create a new issue instead of commenting on closed PR. If you have a question feel free to use our [discussions forum](https://github.com/allure-framework/allure2/discussions)

**Comment by olivia2046** [comment]
> @olivia2046, please create a new issue instead of commenting on closed PR. If you have a question feel free to use our [discussions forum](https://github.com/allure-framework/allure2/discussions)
Got it. I've now switched to a jenkins instance of latest version and the issue is resolved. Thanks.

**Pull request merged**
