### PR TITLE
Allure Xray Plugin smarter status updates for Xray Test Case statuses. 

### LINKED ISSUE #1490: Xray Plugin -> smarter update of statuses
In the moment if you have several tests mapped to one Xray Test Case and 1 fails and the all other pass, the Xray Test Case could be marked PASS or FAIL by luck. There is no guarantee what will be the results.

It would be much better if there is a failing tests the Xray Tests Case to be marked as FAIL.

You can achieve this behavior with smart update of statues. If we replace this block of code:
```
launchesResults.stream()
        .map(LaunchResults::getAllResults)
        .flatMap(Collection::stream)
        .forEach(testResult -> updateTestRunStatuses(jiraService, testResult, statusesMap, testRunsMap));
```

with this one:
```       
final List<TestResult> testReults = launchesResults.stream()
                .map(LaunchResults::getAllResults)
                .flatMap(Collection::stream)
                .collect(Collectors.toList());

final List<TestResult> testPassReults = testReults.stream()
        .filter(it -> statusesMap.get(it.getStatus()) == XRAY_STATUS_PASS)
        .collect(Collectors.toList());
final List<TestResult> testFailReults = testReults.stream()
        .filter(it -> statusesMap.get(it.getStatus()) == XRAY_STATUS_FAIL)
        .collect(Collectors.toList());
final List<TestResult> testToDoReults = testReults.stream()
        .filter(it -> statusesMap.get(it.getStatus()) == XRAY_STATUS_TODO)
        .collect(Collectors.toList());

testToDoReults.forEach(testResult -> updateTestRunStatuses(jiraService, testResult, statusesMap, testRunsMap));
testPassReults.forEach(testResult -> updateTestRunStatuses(jiraService, testResult, statusesMap, testRunsMap));
testFailReults.forEach(testResult -> updateTestRunStatuses(jiraService, testResult, statusesMap, testRunsMap));
```

We would achieve that behavior. We are filtering the results by status. Update ToDo items first, after that PASS items and last the FAIL items.

### PR DESCRIPTION
**Pull request by vhristov5555**
Add smarter status updates for Xray Test Case statuses to Allure Xray Plugin. 
Add test to verify the behaviour.

Fix for #1490

If you have 5 tests pointing to one Xray Test Case and 1 FAIL and 4 PASS only one update with the FAIL state would be done. If you have 5 tests and all are with PASS status only one update with PASS state would be done.

### CODE REVIEW

**Comment by baev** [comment]
@vhristov5555 could you please rebase the PR?

**Comment by vhristov5555** [comment]
I think I am done @baev . Not sure if you had chance to review it.

**Comment by vhristov5555** [comment]
@baev just fix the formating issue.

**Review by baev — APPROVED** [review]

**Comment by vhristov5555** [comment]
I thank you too :) @baev

**Comment by vhristov5555** [comment]
@baev When we could download it from maven ?

**Comment by baev** [comment]
2.17.0 is on the way, will be available within an hour

**Pull request merged**
