### PR TITLE
parseStatus of TrxPlugin to support not executed tests by the IgnoreAttribute

### PR DESCRIPTION
**Pull request by agentran**
#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
@agentran could you please add a test for the change? Just for future regression testing

**Comment by agentran** [comment]
@baev Added to the base test shouldParseResults.

**Review by baev — APPROVED** [review]

**Comment by omer-za** [comment]
@baev when it will be merged and when there's a plan to have a new release?

**Comment by baev** [comment]
@omer-za thanks!

> when there's a plan to have a new release?

I'd say within a week

**Pull request merged**
