### PR TITLE
Bump opencsv from 4.6 to 5.9

### PR DESCRIPTION
**Pull request by kusaeva**
### Context

Migrating to opencsv 5 using this information:
https://sourceforge.net/p/opencsv/support-requests/82/

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Review by A1exKH — APPROVED** [review]
Code LGTM.

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
The functional change is that the header names are now in uppercase. According to `com.opencsv.bean.HeaderColumnNameMappingStrategy#registerBinding`, there is no way to modify the behaviour.

**Comment by baev** [comment]
> header names are now in uppercase

Personally, I'm ok with it. The code will not be reused in Allure 3 since it is written in pure TypeScript. The CSV module has already been implemented for Allure 3 in a much more customizable way. 

If someone needs the old behaviour (with lowercase column names) — please feel free to [create a discussion](https://github.com/orgs/allure-framework/discussions/new?category=ideas-feedback).

**Comment by baev** [comment]
@kusaeva thanks!

**Pull request merged**
