### PR TITLE
Add Turkish Language to language select menu

### PR DESCRIPTION
**Pull request by fatih-sukran**
### Context
Added Turkish Language Option

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by baev** [comment]
I see. The translations were added in https://github.com/allure-framework/allure2/pull/1979

But we forgot to add the option to the menu. This PR fixes that ;)

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
@fatih-sukran thanks!

**Comment by EsmaFonetBT** [comment]
@fatih-sukran I installed allure 2.27 version but I couldn't see TR option. the bug is continuing

**Comment by fatih-sukran** [comment]
> @baev @fatih-sukran I installed allure 2.27 version but I couldn't see TR option. the bug is continuing

Hi @EsmaFonetBT, version 2.27 does not include this fix. I think It will come at 2.28

**Pull request merged**
