### PR TITLE
Add Swedish translations

### PR DESCRIPTION
**Pull request by atg-pablo-widlert**
### Context
Add Swedish translations for Allure

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests (not applicable)

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by atg-pablo-widlert** [comment]
I guess this needs another label [ype:improvement](https://github.com/allure-framework/allure2/labels/type%3Aimprovement) to continue with the automated checks.

**Comment by atg-pablo-widlert** [comment]
@baev Can you review + merge?

**Review by baev — CHANGES_REQUESTED** [review]
Please, add translations for the plugins:

plugins/behaviors-plugin/src/dist/static/index.js
plugins/packages-plugin/src/dist/static/index.js

Then, you need to enable translation in 

allure-generator/src/main/javascript/utils/translation.js

and allow it to be configured via command-line option:

allure-commandline/src/main/java/io/qameta/allure/validator/LanguageValidator.java

**Review by baev — APPROVED** [review]

**Comment by atg-pablo-widlert** [comment]
@baev Can you merge this too? I am not authorized.

**Comment by baev** [comment]
@atg-pablo-widlert thanks!

**Pull request merged**
