### PR TITLE
Bump opencsv from 4.6 to 5.7.1

### PR DESCRIPTION
**Pull request by dr29bart**
#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Review by A1exKH — CHANGES_REQUESTED** [review]
Please, review and update your PR to resolve conflicts.
Also please check build details, because build was failed.

**Comment by kusaeva** [comment]
Maybe this PR will be more actual https://github.com/allure-framework/allure2/pull/2547/

**Comment by baev** [comment]
fixed via https://github.com/allure-framework/allure2/pull/2547

**Comment by baev** [comment]
@dr29bart, thanks anyway!

**Pull request closed without merging**
