### PR TITLE
Introduce single file report mode

### LINKED ISSUE #755: Export Allure Report to a single HTML File
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure Report is only available as long as i have the json files to generate it and keep the terminal open.

#### What is the motivation / use case for changing the behavior?
Need a single HTML file to keep track of for historical information of the report, and can be send as 1 file to the whole team. (e.g February2018_Report.html)

I tried saving the report as Webpage, Complete but the webpage was empty, have loading icons, and 404 not found.

#### Please tell us about your environment:
I'm using allure 2.5.0 and allure-behave
using allure serve {folder} in the terminal to generate the report

And that's all i believe what i am doing

### PR DESCRIPTION
**Pull request by baev**
### Context

The change introduces single file report mode. To generate the report in
single file mode run:

```bash
$ allure generate --single-file allure-results
```

fixes #755

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Review by eroshenkoam — APPROVED** [review]

**Comment by gerganapecanova** [comment]
Is there a way to use this option in Allure Bamboo Plugin?

**Comment by biski** [comment]
I have some concerns about this single file mode. Our reports contain thousands of test cases (because we run them entire weekend) and sometimes have a lot of attachments and reports could be very big, like 5g. Will this single file mode still works? Could you still maintain current mode?

**Comment by baev** [comment]
@biski, please create a discussion https://github.com/orgs/allure-framework/discussions, and I'll be happy to answer!

**Comment by karltiirik** [comment]
@baev, this feature was very missed: useful for cases where you just want to send a report than can be opened in a browser. 

But, I'm missing the "Package" and "Behaviors" view when using the ` --single-file` flag. Console shows  2 `Uncaught ReferenceError: allure is not defined` errors:
Kuvatõmmis 2023-10-18 232449
Kuvatõmmis 2023-10-18 232505
Kuvatõmmis 2023-10-18 232528

This doesn't happen when I don't use the ` --single-file` flag. Let be know if I'm missing something or if I should formulate this into a bug report.

**Comment by anht3889** [comment]
@karltiirik I have the same issue with you when exporting single html file. Have you filed a bug report yet?

**Comment by baev** [comment]
@karltiirik @anht3889 fixed via https://github.com/allure-framework/allure2/pull/2220

**Comment by vydra** [comment]
How do we get history with --single-file option?

**Comment by baev** [comment]
@vydra, it's not yet supported. Please follow https://github.com/orgs/allure-framework/discussions/2127 for the updates.

**Comment by princyyyy** [comment]
@baev how can i share allure-report to someone else in company on URL ?

**Comment by princyyyy** [comment]
@baev yes i know we can archived that through CI, but my requirement is to share report via link in pull request so reviewer can get to know testcases is getting pass, without CI

**Comment by Ajay-Jha** [comment]
Single file generated report not able to bind style.css correctly if we use custom-logo. Old command " allure serve allure-results" still picking the custom logo correctly.

Style_allure

**Comment by adarshmeledam** [comment]
Hi, I am getting a message "--single-file doesn't exist"
Report generated to allure-report folder. But when I opened, it is not loading any data.

**Comment by Ajay-Jha** [comment]
@baev , can you please guide me, how can i use custom logo with this feature

**Pull request merged**
