### PR TITLE
adding indicator for stack trace and english translation implements #501

### PR DESCRIPTION
**Pull request by symonk**
Adding a simple indicator that the statusMessage can be expanded to the user with a new icon + some text.  I am unsure of translations for other language(s) or how we go about implementing those, google translations? so I have added an english translation for now, waiting for your advice there.

### CODE REVIEW

**Comment by baev** [comment]
@symonk we already have some improvements in rft-web2 branch (such change gonna be included in next major release)

image 2018-01-28 16 53 51

**Comment by symonk** [comment]
ah sorry about that, I wasen't too sure

**Comment by baev** [comment]
> ah sorry about that, I wasen't too sure

not a problem, thank you for helping us!

**Comment by symonk** [comment]
no problem :) Front end stuff is tough haha, is the duration copy of any use?

**Comment by baev** [comment]
Linked issue: https://github.com/allure-framework/allure2/issues/395

I have no problem with it, but @just-boris does (as far as I know). Feel free to create separate pull request with the change and lets discuss

**Comment by just-boris** [comment]
Yep, my concern is the same. Extra copy button pollutes the page for no reason.

Instead of exposing an extra button, we can just change the duration format, so it will become copyable. Simple.

**Comment by baev** [comment]
@symonk thanks anyway!

**Pull request closed without merging**
