### PR TITLE
Improved Suite CSV Export Functionality

### PR DESCRIPTION
**Pull request by msb217**
[//]: # (
. Thank you so much for sending us a pull request! 
.
. Make sure you have a clear name for your pull request. 
. The name should start with a capital letter and no dot is required in the end of the sentence.
. To link the request with isses use the following notation: (fixes #123, fixes #321\)
.
. An example of good pull request names:
. - Add Russian translation (fixes #123\)
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

### Context
[//]: # (
Describe the problem or feature in addition to a link to the issues
)

###### Description of Changes
Currently, the export to CSV utility for suites does not support the hierarchy for suites (`parentSuite`, `suite`, `subSuite`) and therefore I have added these labels to the export.

I have also added the columns start/stop date as there are no timestamps with the current export template.

I have also added the labels `testClass`, `testMethod`, and `name` to the list of columns exported with the CSV in order to increase the level of detail and distinction. Due to the addition of these three labels, I have removed the label `fullName `.

I also have refactored `message` -> `description` in order to maintain consistency with the attribute titles.

For the entity TestResult, I have added a method titled `toMap()` which converts the list of labels to a map. I implemented this in order to provide resilience when assigning the labels in the `CsvExportSuite` constructor. For example, `results.getLabels().get(0)`,`results.getLabels().get(1)`, ... could potentially break if the order of labels are not preserved. This is avoided with a map.

###### Reasons for Changes
All of these changes were made with the intention of creating a more organized, detailed, and meaningful CSV export for test suites. For my use case, I have found these changes to be vital.

#### Checklist
- [X] [Sign Allure CLA][cla]
- [ ] Provide unit tests

I apologize, I saw no existing unit tests for CSV export functionality. If needed, I can implement them. If there are any questions surrounding my implementation or things you would like me to change, feel free to ask. Allure has been a pleasure to use - thank you for creating this!

(Also, my apologies for the duplicate pull request - I forgot to change my local config and commited/pr'ed with two separate accounts) - please delete PR #855

[cla]: https://cla-assistant.io/accept/allure-framework/allure2\

### CODE REVIEW

**Comment by msb217** [comment]
Any comments or opinions?

**Comment by baev** [comment]
@msb217 sorry for the delay.

Looks ok for me, please update branch and we good to merge

**Comment by msb217** [comment]
@baev @eroshenkoam Awesome thanks guys, best

**Comment by baev** [comment]
@msb217 thanks1

**Pull request merged**
