### PR TITLE
Fixes If user click on a test items, other previously opened test packages also got expanded. #575

### PR DESCRIPTION
**Pull request by TpSr52**
### Context
I have fixed a bug.  If the user clicks on a test item, other previously opened test packages also got expanded. #575

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by baranoff-ivan** [comment]
Why so much commits for two lines change? Could you delete this pull request and create new one from master branch with just one commit?

**Comment by baev** [comment]
Seems like the issue is not fixed. See demo report https://ci.qameta.io/job/allure2/job/PR-639/Demo_Report/index.html

**Comment by TpSr52** [comment]
@baev I saw the demo report. Previously, when I opened a test category and closed it and later I opened another test category, the previous test category also got expanded. In the demo, it doesn't look like this problem happens anymore.

**Comment by baev** [comment]
try on suites tab

**Comment by TpSr52** [comment]
@baev Ok, I tried it right now. I don't see a problem

**Comment by TpSr52** [comment]
@baev Ok, I see it right now, when I have filtered it, it happened

**Comment by TpSr52** [comment]
Ok, then this pull request doesn't fix anything.
I will think about a solution. It will be great if someone else fixes it or helps me with this issue

**Pull request closed without merging**
