### PR TITLE
Add BitBucket logo for executor info

### PR DESCRIPTION
**Pull request by uarlouski**
### Context
Allure report is missing logo for bitbucket executor

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
@uarlouski thanks!

**Comment by uarlouski** [comment]
@baev could you please share when is next version planned to be released?

**Comment by baev** [comment]
Some time next week, I hope

**Comment by uarlouski** [comment]
@baev hello :) could you please share if you have plans to release allure?

**Pull request merged**
